language: csharp
solution: ./DocumentManagement/DocumentManagement.sln
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.1
before_script:
  - chmod a+x ./build.sh
  - cd ./DocumentManagement
script:
  - dotnet build -c Release -f netcoreapp1.1