language: csharp
solution: ./DocumentManagement/DocumentManagement.sln
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.0-preview3-004056
before_script:
  - chmod a+x ./build.sh
  - cd ./DocumentManagement
script:
  - dotnet build --configuration Release